// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package job

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
	config "helloworld/config"
)

type ParamConfigOption func(p *ParamConfig)

// NewParamConfigWithOptions creates a new ParamConfig with the passed in options set
func NewParamConfigWithOptions(opts ...ParamConfigOption) *ParamConfig {
	p := &ParamConfig{}
	for _, o := range opts {
		o(p)
	}
	return p
}

// NewParamConfigWithOptionsAndDefaults creates a new ParamConfig with the passed in options set starting from the defaults
func NewParamConfigWithOptionsAndDefaults(opts ...ParamConfigOption) *ParamConfig {
	p := &ParamConfig{}
	defaults.MustSet(p)
	for _, o := range opts {
		o(p)
	}
	return p
}

// ToOption returns a new ParamConfigOption that sets the values from the passed in ParamConfig
func (p *ParamConfig) ToOption() ParamConfigOption {
	return func(to *ParamConfig) {
		to.App = p.App
		to.Log = p.Log
		to.Feature = p.Feature
		to.Datastore = p.Datastore
		to.Mysql = p.Mysql
		to.Postgres = p.Postgres
		to.TaskID = p.TaskID
		to.LogDir = p.LogDir
	}
}

// DebugMap returns a map form of ParamConfig for debugging
func (p ParamConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["App"] = helpers.DebugValue(p.App, false)
	debugMap["Log"] = helpers.DebugValue(p.Log, false)
	debugMap["Feature"] = helpers.DebugValue(p.Feature, false)
	debugMap["Datastore"] = helpers.DebugValue(p.Datastore, false)
	debugMap["Mysql"] = helpers.DebugValue(p.Mysql, false)
	debugMap["Postgres"] = helpers.DebugValue(p.Postgres, false)
	debugMap["TaskID"] = helpers.DebugValue(p.TaskID, false)
	debugMap["LogDir"] = helpers.DebugValue(p.LogDir, false)
	return debugMap
}

// ParamConfigWithOptions configures an existing ParamConfig with the passed in options set
func ParamConfigWithOptions(p *ParamConfig, opts ...ParamConfigOption) *ParamConfig {
	for _, o := range opts {
		o(p)
	}
	return p
}

// WithOptions configures the receiver ParamConfig with the passed in options set
func (p *ParamConfig) WithOptions(opts ...ParamConfigOption) *ParamConfig {
	for _, o := range opts {
		o(p)
	}
	return p
}

// WithApp returns an option that can set App on a ParamConfig
func WithApp(app *config.App) ParamConfigOption {
	return func(p *ParamConfig) {
		p.App = app
	}
}

// WithLog returns an option that can set Log on a ParamConfig
func WithLog(log *config.Log) ParamConfigOption {
	return func(p *ParamConfig) {
		p.Log = log
	}
}

// WithFeature returns an option that can set Feature on a ParamConfig
func WithFeature(feature *config.Feature) ParamConfigOption {
	return func(p *ParamConfig) {
		p.Feature = feature
	}
}

// WithDatastore returns an option that can set Datastore on a ParamConfig
func WithDatastore(datastore *config.DataStore) ParamConfigOption {
	return func(p *ParamConfig) {
		p.Datastore = datastore
	}
}

// WithMysql returns an option that can set Mysql on a ParamConfig
func WithMysql(mysql *config.Mysql) ParamConfigOption {
	return func(p *ParamConfig) {
		p.Mysql = mysql
	}
}

// WithPostgres returns an option that can set Postgres on a ParamConfig
func WithPostgres(postgres *config.Postgres) ParamConfigOption {
	return func(p *ParamConfig) {
		p.Postgres = postgres
	}
}

// WithTaskID returns an option that can set TaskID on a ParamConfig
func WithTaskID(taskID string) ParamConfigOption {
	return func(p *ParamConfig) {
		p.TaskID = taskID
	}
}

// WithLogDir returns an option that can set LogDir on a ParamConfig
func WithLogDir(logDir string) ParamConfigOption {
	return func(p *ParamConfig) {
		p.LogDir = logDir
	}
}
