app:
  name: "helloworld"
  version: '1.0.0'
  run_mode: 'dev' # 运行模式：dev 为开发和调试模式（输出的日志为 plain text 格式；开启 pprof；），pro 为线上模式（输出的日志为 json 格式；关闭 pprof）

logger:
#  log_level: 'trace'
  log_level: 'debug'

postgres:
  uri: ""

feature:
  shutdown_grace_period: 10s # 接收到终止信号后等待多久才彻底停止程序，这个时间用于响应存量的服务并释放资源

datastore:
  engine: "psql" # 使用哪个数据库引擎，引擎对应的配置放下面: mysql, psql；不需要使用数据库，则填入 no

psql:
  host: '127.0.0.1'
  port: 5432
  db_name: 'postgres'
  db_user: 'postgres'
  db_password: ''
  max_idle_connections: 50
  max_open_connections: 100
  max_connection_life_time: 10s

mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: '12345678'
  db_name: 'test'
  max_idle_connections: 50
  max_open_connections: 100
  max_connection_life_time: 10s


