app:
  name: "helloworld"
  version: '1.0.0'
  run_mode: 'dev' # 运行模式：dev 为开发和调试模式（输出的日志为 plain text 格式；开启 pprof；），pro 为线上模式（输出的日志为 json 格式；关闭 pprof）

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
  url: ""

feature:
  shutdown_grace_period: 0s # 接收到终止信号后等待多久才彻底停止程序，这个时间用于响应存量的服务并释放资源

datastore:
  engine: "mysql" # 使用哪个数据库引擎，引擎对应的配置放下面，none 表示不使用数据库

mysql:
  host: '127.0.0.1'
  username: 'root'
  password: '12345678'
  database: 'test'
  max_idle_connections: 50
  max_open_connections: 100
  max_connection_life_time: 10s